DEBUG:core:POX 0.5.0 (eel) going up...
DEBUG:core:Running on CPython (2.7.18rc1/Apr 7 2020 12:05:55)
DEBUG:core:Platform is Linux-5.4.0-48-generic-x86_64-with-Ubuntu-20.04-focal
INFO:core:POX 0.5.0 (eel) is up.
ERROR:openflow.of_01:Error 98 while binding 0.0.0.0:6653: Address already in use
ERROR:openflow.of_01: You may have another controller running.
ERROR:openflow.of_01: Use openflow.of_01 --port=<port> to run POX on another port.
